export const GET_PRODUCTS_FETCHING = "GET_PRODUCTS_FETCHING";
export const GET_PRODUCTS_FULFILLED = "GET_PRODUCTS_FULFILLED";
export const GET_PRODUCTS_REJECTED = "GET_PRODUCTS_REJECTED";

export const GET_ONE_PRODUCT_FETCHING = "GET_ONE_PRODUCT_FETCHING";
export const GET_ONE_PRODUCT_FULFILLED = "GET_ONE_PRODUCT_FULFILLED";
export const GET_ONE_PRODUCT_REJECTED = "GET_ONE_PRODUCT_REJECTED";

export const ADD_PRODUCT_FETCHING = "ADD_PRODUCT_FETCHING";
export const ADD_PRODUCT_FULFILLED = "ADD_PRODUCT_FULFILLED";
export const ADD_PRODUCT_REJECTED = "ADD_PRODUCT_REJECTED";

export const UPDATE_PRODUCT_FETCHING = "UPDATE_PRODUCT_FETCHING";
export const UPDATE_PRODUCT_FULFILLED = "UPDATE_PRODUCT_FULFILLED";
export const UPDATE_PRODUCT_REJECTED = "UPDATE_PRODUCT_REJECTED";

export const DELETE_PRODUCT_FETCHING = "DELETE_PRODUCT_FETCHING";
export const DELETE_PRODUCT_FULFILLED = "DELETE_PRODUCT_FULFILLED";
export const DELETE_PRODUCT_REJECTED = "DELETE_PRODUCT_REJECTED";

export const ERROR_TO_DEFAULT = "ERROR_TO_DEFAULT";
