export const GET_SALES_FETCHING = "GET_SALES_FETCHING";
export const GET_SALES_FULFILLED = "GET_SALES_FULFILLED";
export const GET_SALES_REJECTED = "GET_SALES_REJECTED";

export const ADD_SALE_FETCHING = "ADD_SALE_FETCHING";
export const ADD_SALE_FULFILLED = "ADD_SALE_FULFILLED";
export const ADD_SALE_REJECTED = "ADD_SALE_REJECTED";

export const UPDATE_SALE_FETCHING = "UPDATE_SALE_FETCHING";
export const UPDATE_SALE_FULFILLED = "UPDATE_SALE_FULFILLED";
export const UPDATE_SALE_REJECTED = "UPDATE_SALE_REJECTED";

export const ERROR_TO_DEFAULT = "ERROR_TO_DEFAULT";
